# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='cached_images')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.CharField(max_length=255)),
                ('feed_title', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField()),
                ('language', models.CharField(blank=True, max_length=255)),
                ('copyright', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('managingEditor', models.EmailField(blank=True, max_length=254)),
                ('webMaster', models.EmailField(blank=True, max_length=254)),
                ('pubDate', models.DateTimeField()),
                ('lastBuildDate', models.DateTimeField()),
                ('generator', models.CharField(blank=True, max_length=255)),
                ('docs', models.URLField(blank=True)),
                ('cloud', models.TextField(blank=True)),
                ('ttl', models.IntegerField(default=3600)),
                ('icon', models.FileField(blank=True, upload_to='xfeeds/feed_icons/')),
                ('rating', models.CharField(blank=True, max_length=255)),
                ('textInput', models.CharField(blank=True, max_length=255)),
                ('skipHours', models.IntegerField(default=0)),
                ('skipDays', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xfeeds.CachedImage')),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('feeds', models.ManyToManyField(to='xfeeds.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255)),
                ('pubDate', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=255)),
                ('comments', models.URLField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xfeeds.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='FeedItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(to='xfeeds.FeedItem')),
            ],
        ),
        migrations.CreateModel(
            name='SeenItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
